
// action login với user
const LOGIN_USER = "LOGIN_USER";
const LOGIN_USER_SUCESS = "LOGIN_USER_SUCESS";
const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
// action login với user google
const LOGIN_USER_GOOGLE = "LOGIN_USER_GOOGLE";
const LOGIN_USER_GOOGLE_SUCCESS = "LOGIN_USER_GOOGLE_SUCCESS";
const LOGIN_USER_GOOGLE_ERROR = "LOGIN_USER_GOOGLE_ERROR";

// exports.LOGIN_USER = LOGIN_USER;
// exports.LOGIN_USER_SUCESS = LOGIN_USER_SUCESS;
// exports.LOGIN_USER_ERROR = LOGIN_USER_ERROR;
// exports.LOGIN_USER_GOOGLE = LOGIN_USER_GOOGLE;
// exports.LOGIN_USER_GOOGLE_SUCCESS = LOGIN_USER_GOOGLE_SUCCESS;
// exports.LOGIN_USER_GOOGLE_ERROR = LOGIN_USER_GOOGLE_ERROR;

export default {
    LOGIN_USER,
    LOGIN_USER_SUCESS,
    LOGIN_USER_ERROR,
    LOGIN_USER_GOOGLE,
    LOGIN_USER_GOOGLE_SUCCESS,
    LOGIN_USER_GOOGLE_ERROR
}